
(()=>{"use strict";
const BUILD={version:"3.0.0-alpha",id:"IL-A3.0-KEEPER-FOUNDATION"},SAVE="ilm.a30",IMG={item:"images/item.png",hero:"images/hero.png"};
const D={items:{crudeAxe:{n:"Crude Axe",i:"🪓",slot:"woodTool",v:25,type:"tool"},copperAxe:{n:"Copper Axe",i:"🪓",slot:"woodTool",v:180,type:"tool"},crackedPickaxe:{n:"Cracked Pickaxe",i:"⛏️",slot:"mineTool",v:25,type:"tool"},copperPickaxe:{n:"Copper Pickaxe",i:"⛏️",slot:"mineTool",v:180,type:"tool"},reedRod:{n:"Reed Rod",i:"🎣",slot:"fishTool",v:25,type:"tool"},fieldKnife:{n:"Field Knife",i:"🔪",slot:"processTool",v:25,type:"tool"},trainingSword:{n:"Training Sword",i:"🗡️",slot:"mainHand",pow:2,v:40,type:"weapon"},oakShortbow:{n:"Oak Shortbow",i:"🏹",slot:"mainHand",pow:3,v:120,type:"weapon"},paddedVest:{n:"Padded Vest",i:"🥋",slot:"body",def:2,hp:1,v:90,type:"armor"},copperRing:{n:"Copper Ring",i:"💍",slot:"ring",v:120,type:"jewelry",xpBonus:.03},donkey:{n:"Donkey",i:"🐴",slot:"mount",speed:.9,v:350,type:"mount"},foxPet:{n:"Fox Pet",i:"🦊",slot:"pet",v:0,type:"pet",bound:true},oakLog:{n:"Oak Log",i:"🪵",v:6,type:"wood"},elderLog:{n:"Elder Log",i:"🌳",v:80,type:"wood"},copperOre:{n:"Copper Ore",i:"🟠",v:8,type:"ore"},ironOre:{n:"Iron Ore",i:"🪨",v:14,type:"ore"},silverOre:{n:"Silver Ore",i:"⚪",v:95,type:"ore"},copperBar:{n:"Copper Bar",i:"🟧",v:22,type:"bar"},ironBar:{n:"Iron Bar",i:"⬛",v:44,type:"bar"},riverMinnow:{n:"River Minnow",i:"🐟",v:4,type:"fish"},cookedMinnow:{n:"Cooked Minnow",i:"🍢",heal:8,v:9,type:"food"},shoreBass:{n:"Shore Bass",i:"🐠",v:22,type:"fish"},grilledBass:{n:"Grilled Bass",i:"🍣",heal:18,v:44,type:"food"},ratCarcass:{n:"Rat Carcass",i:"🐀",v:2,type:"carcass"},ratHide:{n:"Rat Hide",i:"🟫",v:5,type:"hide"},smallBone:{n:"Small Bone",i:"🦴",v:4,type:"bone"},goblinEar:{n:"Goblin Ear",i:"👂",v:45,type:"component"},ashCharm:{n:"Ash Charm",i:"🧿",v:90,type:"component"},forestEgg:{n:"Forest Egg",i:"🥚",v:1500,type:"egg"}},
skills:["hitpoints","melee","ranged","magic","woodcutting","mining","fishing","gathering","processing","smithing","fletching","cooking","crafting","leadership"],slots:{mainHand:"Main Hand",offHand:"Off Hand",body:"Body",head:"Head",cape:"Cape",neck:"Neck",legs:"Legs",gloves:"Gloves",boots:"Boots",ring:"Ring",woodTool:"Wood Tool",mineTool:"Mine Tool",fishTool:"Fish Tool",processTool:"Knife",mount:"Mount",pet:"Pet"},
actions:{oak:{n:"Chop Oak",i:"🌲",cat:"Gathering",s:"woodcutting",tool:"crudeAxe",sec:6,xp:8,out:[["oakLog",1,1,1],["forestEgg",1,1,.0006]],d:"Reliable starter logs and rare forest eggs."},elder:{n:"Cut Elder Bough",i:"🌳",cat:"Gathering",s:"woodcutting",tool:"copperAxe",sec:18,xp:35,out:[["elderLog",1,2,1],["forestEgg",1,1,.004]],d:"Ancient wood from the Elder Woods."},copper:{n:"Mine Copper",i:"⛏️",cat:"Gathering",s:"mining",tool:"crackedPickaxe",sec:7,xp:9,out:[["copperOre",1,1,1]],d:"Basic ore for first bars."},iron:{n:"Mine Iron",i:"⛏️",cat:"Gathering",s:"mining",tool:"crackedPickaxe",sec:9,xp:13,out:[["ironOre",1,1,1]],d:"Better ore from Irondeep."},silver:{n:"Mine Silver Hollow",i:"⚪",cat:"Gathering",s:"mining",tool:"copperPickaxe",sec:16,xp:30,out:[["silverOre",1,1,1]],d:"Rare silver in Frostgate."},fish:{n:"Fish Minnows",i:"🐟",cat:"Gathering",s:"fishing",tool:"reedRod",sec:7,xp:9,out:[["riverMinnow",1,2,.9]],d:"Basic food source."},bass:{n:"Fish Shore Bass",i:"🐠",cat:"Gathering",s:"fishing",tool:"reedRod",sec:12,xp:20,out:[["shoreBass",1,1,.85]],d:"Better fish from Saltshore."},rats:{n:"Clear Rats",i:"🐀",cat:"Combat",s:"melee",enemy:"rat",sec:9,xp:11,gold:[2,5],out:[["ratCarcass",1,1,.7]],d:"Starter combat and carcasses."},goblins:{n:"Fight Goblin Scouts",i:"👺",cat:"Combat",s:"melee",enemy:"goblin",sec:12,xp:16,gold:[4,10],out:[["goblinEar",1,1,.16]],d:"Better combat rewards."},bandits:{n:"Ambush Ash Bandits",i:"🥷",cat:"Combat",s:"melee",enemy:"bandit",sec:18,xp:26,gold:[9,22],out:[["ashCharm",1,1,.08],["smallBone",1,2,.25]],d:"Dangerous western combat."},process:{n:"Process Rat Carcasses",i:"🔪",cat:"Production",s:"processing",tool:"fieldKnife",sec:5,xp:6,in:[["ratCarcass",1]],out:[["ratHide",1,1,.8],["smallBone",1,2,.65]],d:"Turn carcasses into materials."}},
recipes:{cook:{n:"Cook Minnow",i:"🍢",s:"cooking",lvl:1,xp:7,in:[["riverMinnow",1]],out:[["cookedMinnow",1]]},bass:{n:"Grill Bass",i:"🍣",s:"cooking",lvl:5,xp:18,in:[["shoreBass",1],["oakLog",1]],out:[["grilledBass",1]]},bar:{n:"Smelt Copper",i:"🔥",s:"smithing",lvl:1,xp:8,in:[["copperOre",2]],out:[["copperBar",1]]},ironbar:{n:"Smelt Iron",i:"🔥",s:"smithing",lvl:4,xp:18,in:[["ironOre",2],["copperBar",1]],out:[["ironBar",1]]},axe:{n:"Forge Copper Axe",i:"🪓",s:"smithing",lvl:2,xp:20,in:[["copperBar",2],["oakLog",1],["crudeAxe",1]],out:[["copperAxe",1]]},pick:{n:"Forge Copper Pickaxe",i:"⛏️",s:"smithing",lvl:2,xp:20,in:[["copperBar",2],["oakLog",1],["crackedPickaxe",1]],out:[["copperPickaxe",1]]},bow:{n:"Fletch Oak Shortbow",i:"🏹",s:"fletching",lvl:1,xp:14,in:[["oakLog",2]],out:[["oakShortbow",1]]},vest:{n:"Tailor Padded Vest",i:"🥋",s:"processing",lvl:2,xp:16,in:[["ratHide",3]],out:[["paddedVest",1]]},ring:{n:"Craft Copper Ring",i:"💍",s:"crafting",lvl:3,xp:22,in:[["copperBar",1],["silverOre",1]],out:[["copperRing",1]]}},enemies:{rat:{n:"City Rat",hp:10,dmg:[1,3]},goblin:{n:"Goblin Scout",hp:22,dmg:[2,6]},bandit:{n:"Ash Bandit",hp:38,dmg:[4,9]}},quests:{ironRoads:{n:"The Iron Roads",origin:"Irondeep",req:{mining:5},unlock:"frost",d:"Repair the northern road and unlock Frostgate."},elderCall:{n:"Call of Elder Boughs",origin:"Greenhaven",req:{woodcutting:8},unlock:"elder",d:"Learn the old forest route."},ashTrial:{n:"Trial of Ash",origin:"Emberfall",req:{melee:7},unlock:"ashpit",d:"Earn passage into the ash hollows."}},cities:{king:{n:"Kingswatch",i:"🏰",sub:"Start",x:50,y:50,act:["oak","copper","fish","rats","process"],shop:["donkey","trainingSword"]},iron:{n:"Irondeep",i:"⛰️",sub:"Mining city",x:50,y:18,act:["iron","rats"],shop:[]},green:{n:"Greenhaven",i:"🌲",sub:"Forest city",x:78,y:48,act:["oak","fish","goblins"],shop:[]},salt:{n:"Saltshore",i:"⚓",sub:"Coastal port",x:50,y:80,act:["fish","bass"],shop:[]},ember:{n:"Emberfall",i:"🔥",sub:"Western frontier",x:22,y:60,act:["rats","goblins","bandits"],shop:[]},frost:{n:"Frostgate",i:"❄️",sub:"Locked pass",x:50,y:5,lock:"ironRoads",act:["silver"],shop:[]},elder:{n:"Elder Woods",i:"🦅",sub:"Locked forest",x:92,y:36,lock:"elderCall",act:["elder"],shop:[]},ashpit:{n:"Ash Hollow",i:"🌋",sub:"Locked hollow",x:8,y:77,lock:"ashTrial",act:["bandits"],shop:[]}},roads:[["king","iron"],["king","green"],["king","salt"],["king","ember"],["iron","frost"],["green","elder"],["ember","ashpit"]]};
let save=null,drag=null,toastTimer=null;const app=document.getElementById("app"),now=()=>Date.now(),rand=(a,b)=>a+Math.floor(Math.random()*(b-a+1)),qty=(b,id)=>Number((b||{})[id]||0),inc=(b,id,n)=>{b[id]=Number(b[id]||0)+n;if(b[id]<=0)delete b[id]},lvl=xp=>Math.max(1,Math.floor(Math.sqrt((xp||0)/45))+1),fmt=ms=>{const s=Math.max(0,Math.floor(ms/1000)),m=Math.floor(s/60),r=s%60;return m?`${m}:${String(r).padStart(2,"0")}`:`${r}s`},it=id=>D.items[id]||{n:id,i:"◼️",v:0,type:"unknown"},esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const UI={panel:(t,b)=>`<section class="panel"><div class="panelHead"><h2>${t}</h2>${save.screen!=="home"?`<button class="small" data-screen="home">Home</button>`:""}</div>${b}</section>`,row:(main,btn="")=>`<div class="row"><div class="rowMain">${main}</div>${btn}</div>`,btn:(txt,attr)=>`<button class="small" ${attr}>${txt}</button>`};
function fresh(){save={name:"The Iron Wolves",gold:50,hardened:true,screen:"home",city:"king",action:null,lastRegen:now(),quests:[],ach:[],daily:{a:0,c:0,xp:0},bank:{crudeAxe:1,crackedPickaxe:1,reedRod:1,fieldKnife:1,trainingSword:1},chat:[["system","Welcome to Idle Legends."],["system",`Build ${BUILD.version}`]],map:{x:0,y:0,z:1},adv:{name:"Rowan",hp:10,skills:Object.fromEntries(D.skills.map(s=>[s,{xp:s==="hitpoints"?2025:0}])),eq:Object.fromEntries(Object.keys(D.slots).map(s=>[s,null]))}};persist()}
function load(){try{save=JSON.parse(localStorage.getItem(SAVE))}catch{}}
function persist(){localStorage.setItem(SAVE,JSON.stringify(save))}
function add(ch,msg){save.chat.push([ch,msg]);save.chat=save.chat.slice(-160)}
function toast(msg){document.querySelector(".toast")?.remove();let e=document.createElement("div");e.className="toast";e.textContent=msg;document.body.appendChild(e);clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.remove(),1600)}
function maxHp(){let b=0;Object.values(save.adv.eq).forEach(id=>b+=it(id).hp||0);return lvl(save.adv.skills.hitpoints.xp)+b}
function xpMult(){let m=1;Object.values(save.adv.eq).forEach(id=>m+=it(id).xpBonus||0);return m}
function regen(){let ticks=Math.floor((now()-(save.lastRegen||now()))/30000);if(ticks>0){save.adv.hp=Math.min(maxHp(),(save.adv.hp||maxHp())+ticks);save.lastRegen+=ticks*30000}}
function owns(id){return qty(save.bank,id)>0||Object.values(save.adv.eq).includes(id)}
function canArea(id){let c=D.cities[id];return !c.lock||save.quests.includes(c.lock)}
function valid(aid){let a=D.actions[aid];if(a.tool&&!owns(a.tool))return`Need ${it(a.tool).n}`;if(a.enemy&&!save.adv.eq.mainHand)return"Equip a weapon first";if(a.in?.some(([id,n])=>qty(save.bank,id)<n))return"Need resources";return null}
function start(aid){resolve();let e=valid(aid);if(e)return toast(e);save.action={aid,start:now(),city:save.city};save.screen="home";add("system",`${save.adv.name} started ${D.actions[aid].n}.`);persist();render()}
function stop(){resolve();save.action=null;add("system","Assignment stopped.");persist();render()}
function resolve(){if(!save)return;regen();if(!save.action)return;let a=D.actions[save.action.aid],n=Math.floor(Math.min(now()-save.action.start,8*3600000)/(a.sec*1000));if(n<=0)return;let done=0;for(let i=0;i<n;i++){if(a.in){if(a.in.some(([id,num])=>qty(save.bank,id)<num))break;a.in.forEach(([id,num])=>inc(save.bank,id,-num))}if(a.enemy&&!fight(a))break;done++}if(done){for(let i=0;i<done;i++){if(a.gold)save.gold+=rand(a.gold[0],a.gold[1]);(a.out||[]).forEach(([id,min,max,p])=>{if(Math.random()<=p)inc(save.bank,id,rand(min,max))})}let gained=Math.floor(a.xp*done*xpMult());save.adv.skills[a.s].xp+=gained;save.daily.a=(save.daily.a||0)+done;save.daily.xp=(save.daily.xp||0)+gained;save.action.start+=done*a.sec*1000;add("loot",`${a.n}: ${done} complete, +${gained} ${a.s} XP.`);checkAch()}persist()}
function fight(a){let e=D.enemies[a.enemy],hp=save.adv.hp,ehp=e.hp,pow=lvl(save.adv.skills[a.s].xp)+(it(save.adv.eq.mainHand).pow||1);for(let r=0;r<40&&hp>0&&ehp>0;r++){ehp-=rand(1,Math.max(2,pow));if(ehp<=0)break;hp-=rand(e.dmg[0],e.dmg[1]);let food=qty(save.bank,"grilledBass")?"grilledBass":qty(save.bank,"cookedMinnow")?"cookedMinnow":null;if(food&&hp>0&&hp<=maxHp()*.35){inc(save.bank,food,-1);hp=Math.min(maxHp(),hp+it(food).heal);add("combat",`Ate ${it(food).n}.`)}}if(hp<=0){save.adv.hp=Math.ceil(maxHp()*.35);add("combat",`${save.adv.name} was defeated.`);return false}save.adv.hp=Math.min(maxHp(),hp+1);save.adv.skills.hitpoints.xp+=Math.max(1,Math.floor(a.xp*.35));return true}
function equip(id){let x=it(id);if(!x.slot)return toast("Cannot equip");if(qty(save.bank,id)<=0)return toast("Not in bank");inc(save.bank,id,-1);let old=save.adv.eq[x.slot];if(old)inc(save.bank,old,1);save.adv.eq[x.slot]=id;add("system",`Equipped ${x.n}.`);persist();render()}
function unequip(slot){let old=save.adv.eq[slot];if(!old)return;inc(save.bank,old,1);save.adv.eq[slot]=null;persist();render()}
function craft(id){let r=D.recipes[id];if(lvl(save.adv.skills[r.s].xp)<r.lvl)return toast("Need level");for(let [i,n] of r.in)if(qty(save.bank,i)<n)return toast(`Need ${it(i).n}`);r.in.forEach(([i,n])=>inc(save.bank,i,-n));r.out.forEach(([i,n])=>inc(save.bank,i,n));save.adv.skills[r.s].xp+=r.xp;save.daily.c=(save.daily.c||0)+1;add("system",`Crafted ${r.n}.`);checkAch();persist();render()}
function buy(id){if(save.gold<it(id).v)return toast("Not enough gold");save.gold-=it(id).v;inc(save.bank,id,1);add("trade",`Bought ${it(id).n}.`);persist();render()}
function sell(id){if(qty(save.bank,id)<=0)return;if(it(id).bound)return toast("Bound item");inc(save.bank,id,-1);let price=Math.max(1,Math.floor(it(id).v*.94));save.gold+=price;add("trade",`Sold ${it(id).n} for ${price}g.`);persist();render()}
function completeQuest(id){let q=D.quests[id];if(save.quests.includes(id))return;for(let [s,l] of Object.entries(q.req))if(lvl(save.adv.skills[s].xp)<l)return toast(`Need ${s} ${l}`);save.quests.push(id);add("system",`Quest complete: ${q.n}. ${D.cities[q.unlock].n} unlocked.`);persist();render()}
function hatch(){if(qty(save.bank,"forestEgg")<=0)return toast("No Forest Egg");inc(save.bank,"forestEgg",-1);inc(save.bank,"foxPet",1);add("loot","A Fox Pet hatched from the Forest Egg.");persist();render()}
function checkAch(){let defs={wood5:["Novice Woodcutter",lvl(save.adv.skills.woodcutting.xp)>=5],mine5:["Stonehand",lvl(save.adv.skills.mining.xp)>=5],first100:["First 100 Gold",save.gold>=100],craft5:["Workshop Spark",save.daily.c>=5]};for(let [id,[n,ok]] of Object.entries(defs))if(ok&&!save.ach.includes(id)){save.ach.push(id);add("system",`Achievement: ${n}`)}}
function render(){if(!save){login();return}resolve();app.innerHTML=`<div class="game">${top()}${action()}<main class="content">${screen()}</main>${tabs()}</div>`;bind();if(save.screen==="map")setTimeout(()=>{fitMap();applyMap()},0);live()}
function login(){app.innerHTML=`<section class="login"><div class="loginCard"><div class="mark">👑</div><h1>Idle Legends</h1><p>Keeper foundation: reusable UI pieces, deeper content, quests, pets, achievements, equipment, crafting, combat, map, market, and log.</p><div class="build">Alpha ${BUILD.version}<br>${BUILD.id}</div><input id="exp" class="field" value="The Iron Wolves"><input id="adv" class="field" value="Rowan"><button class="primary" id="begin">Begin</button></div></section>`;document.getElementById("begin").onclick=()=>{fresh();save.name=document.getElementById("exp").value||save.name;save.adv.name=document.getElementById("adv").value||save.adv.name;persist();render()}}
function top(){return`<header class="top"><div class="crest">👑</div><div class="title"><b>${esc(save.name)}</b><span>${save.hardened?"Hardened":"Market"} · ${BUILD.version}</span></div><div class="resource"><div class="pill">🪙 ${save.gold}</div><div class="pill">❤️ ${save.adv.hp}/${maxHp()}</div></div></header>`}
function action(){let a=save.action?D.actions[save.action.aid]:null;return`<section class="action"><div class="actionIcon">${a?a.i:"🧭"}</div><div><b id="actName">${a?a.n:"Idle"}</b><span id="actTime">${a?"":"No assignment"}</span><div class="prog"><div class="bar" id="actBar"></div></div></div>${a?`<button class="small" data-stop>Stop</button>`:`<button class="small" data-screen="map">Map</button>`}</section>`}
function screen(){return({home,actions,bank,equip:equipPanel,skills,craft:craftPanel,more,map,market,combat,log,settings,quests,pets,achievements}[save.screen]||home)()}
function home(){let c=D.cities[save.city];return UI.panel("Home",`<div class="grid"><button class="card" data-screen="actions"><span class="ico">⚡</span><h3>Actions</h3><p>${c.i} ${c.n}</p></button><button class="card" data-screen="map"><span class="ico">🗺️</span><h3>Map</h3><p>Choose area</p></button><button class="card" data-screen="quests"><span class="ico">📜</span><h3>Quests</h3><p>${save.quests.length}/${Object.keys(D.quests).length} complete</p></button><button class="card" data-screen="achievements"><span class="ico">🏆</span><h3>Achievements</h3><p>${save.ach.length} earned</p></button></div><h3>Daily Track</h3>${daily()}<h3>Quick Actions</h3>${D.cities[save.city].act.slice(0,4).map(actionRow).join("")}<h3>Recent Log</h3>${logLines(5)}`)}
function daily(){return UI.row(`<b>Today</b><span>${save.daily.a||0}/25 actions · ${save.daily.c||0}/10 crafts · ${save.daily.xp||0}/1000 XP</span>`)}
function actions(){let c=D.cities[save.city],groups={};c.act.forEach(id=>{let a=D.actions[id];(groups[a.cat]||=[]).push(id)});return UI.panel(`${c.i} ${c.n}`,Object.entries(groups).map(([g,ids])=>`<h3>${g}</h3>${ids.map(actionRow).join("")}`).join("")+shopRows(c))}
function actionRow(id){let a=D.actions[id];return UI.row(`<b>${a.i} ${a.n}</b><span>${a.d} · ${a.sec}s · ${a.s}</span>${a.tool?`<span class="tag">Needs ${it(a.tool).n}</span>`:""}${a.enemy?`<span class="tag">${D.enemies[a.enemy].n}</span>`:""}`,UI.btn("Start",`data-start="${id}"`))}
function shopRows(c){return c.shop.length?`<h3>Local Shop</h3>${c.shop.map(id=>UI.row(`<b>${it(id).i} ${it(id).n}</b><span>${it(id).v} gold</span>`,UI.btn("Buy",`data-buy="${id}"`))).join("")}`:""}
function bank(){let e=Object.entries(save.bank).filter(([,n])=>n>0);return UI.panel("Bank",`<p class="muted">Shared Expedition Bank. Tap gear to equip. Tap resources to sell one.</p><div class="itemGrid">${e.map(([id,n])=>`<button class="item" data-item="${id}"><img src="${IMG.item}"><span>${it(id).i} ${it(id).n}</span><b>${n}</b></button>`).join("")}</div>`)}
function equipPanel(){return UI.panel("Equipment",`<div class="slotGrid">${Object.entries(D.slots).map(([s,l])=>`<button class="slot" data-unequip="${s}"><b>${l}</b><span>${save.adv.eq[s]?`<img src="${IMG.item}">${it(save.adv.eq[s]).n}`:"Empty"}</span></button>`).join("")}</div><h3>Equip From Bank</h3>${Object.entries(save.bank).filter(([id])=>it(id).slot).map(([id,n])=>UI.row(`<b>${it(id).i} ${it(id).n}</b><span>x${n} · ${it(id).type}</span>`,UI.btn("Equip",`data-equip="${id}"`))).join("")||"<p class='muted'>No equippable items.</p>"}`)}
function skills(){return UI.panel("Skills",D.skills.map(s=>UI.row(`<b>${s}</b><span>Level ${lvl(save.adv.skills[s].xp)} · ${save.adv.skills[s].xp} XP</span>`)).join(""))}
function craftPanel(){return UI.panel("Crafting",Object.entries(D.recipes).map(([id,r])=>UI.row(`<b>${r.i} ${r.n}</b><span>${r.s} ${r.lvl} · ${r.in.map(([i,n])=>`${n} ${it(i).n}`).join(", ")} → ${r.out.map(([i,n])=>`${n} ${it(i).n}`).join(", ")}</span>`,UI.btn("Make",`data-craft="${id}"`))).join(""))}
function market(){return UI.panel("Market",["donkey","trainingSword","cookedMinnow","paddedVest","copperAxe","copperPickaxe"].map(id=>UI.row(`<b>${it(id).i} ${it(id).n}</b><span>${it(id).v} gold</span>`,UI.btn("Buy",`data-buy="${id}"`))).join(""))}
function combat(){return UI.panel("Combat",`<p class="muted">Equip a weapon before fighting.</p>${["rats","goblins","bandits"].map(actionRow).join("")}`)}
function quests(){return UI.panel("Quests",Object.entries(D.quests).map(([id,q])=>{let done=save.quests.includes(id),can=Object.entries(q.req).every(([s,l])=>lvl(save.adv.skills[s].xp)>=l);return UI.row(`<b>${done?"✅":"📜"} ${q.n}</b><span>${q.d}</span><span>Origin: ${q.origin} · Requires ${Object.entries(q.req).map(([s,l])=>`${s} ${l}`).join(", ")}</span>`,UI.btn(done?"Done":can?"Complete":"Locked",`data-quest="${id}" ${done||!can?"disabled":""}`))}).join(""))}
function pets(){return UI.panel("Pets",UI.row(`<b>🥚 Forest Egg</b><span>Hatch for a chance at a companion.</span>`,UI.btn("Hatch","data-hatch"))+Object.entries(save.bank).filter(([id])=>it(id).type==="pet").map(([id,n])=>UI.row(`<b>${it(id).i} ${it(id).n}</b><span>x${n}</span>`,UI.btn("Equip",`data-equip="${id}"`))).join(""))}
function achievements(){let defs=[["wood5","Novice Woodcutter","Reach Woodcutting 5"],["mine5","Stonehand","Reach Mining 5"],["first100","First 100 Gold","Hold 100 gold"],["craft5","Workshop Spark","Craft 5 items"]];return UI.panel("Achievements",defs.map(([id,n,d])=>`<div class="row ${save.ach.includes(id)?"done":""}"><div class="rowMain"><b>${save.ach.includes(id)?"🏆":"🔒"} ${n}</b><span>${d}</span></div></div>`).join(""))}
function log(){return UI.panel("World Log",`<div class="chatLog">${logLines(60)}</div>`)}
function logLines(n){return save.chat.slice(-n).reverse().map(l=>`<div class="chatLine"><span>[${l[0]}]</span> ${esc(l[1])}</div>`).join("")}
function more(){return UI.panel("More",`<div class="moreGrid"><button class="card" data-screen="market"><span class="ico">⚖️</span><h3>Market</h3></button><button class="card" data-screen="combat"><span class="ico">⚔️</span><h3>Combat</h3></button><button class="card" data-screen="quests"><span class="ico">📜</span><h3>Quests</h3></button><button class="card" data-screen="pets"><span class="ico">🐾</span><h3>Pets</h3></button><button class="card" data-screen="achievements"><span class="ico">🏆</span><h3>Achievements</h3></button><button class="card" data-screen="settings"><span class="ico">🔧</span><h3>Settings</h3></button><button class="card" data-screen="log"><span class="ico">💬</span><h3>Log</h3></button></div>`)}
function settings(){return UI.panel("Settings",`<p class="muted">Alpha ${BUILD.version}<br>${BUILD.id}</p><button class="danger" data-reset>Reset Local Save</button>`)}
function map(){return UI.panel("Map",`<div class="mapBox" id="mapBox"><div class="world" id="world">${roads()}${Object.entries(D.cities).map(([id,c])=>{let p=mpos(c),locked=!canArea(id);return`<button class="city ${id===save.city?"sel":""} ${locked?"locked":""}" data-city="${id}" style="left:${p.x}px;top:${p.y}px"><i>${c.i}</i><b>${c.n}</b><span>${locked?"Quest locked":c.sub}</span></button>`}).join("")}${hero()}</div></div>`)}
function roads(){return D.roads.map(([a,b])=>{let A=mpos(D.cities[a]),B=mpos(D.cities[b]),dx=B.x-A.x,dy=B.y-A.y,len=Math.hypot(dx,dy),ang=Math.atan2(dy,dx)*180/Math.PI;return`<div class="road" style="left:${A.x}px;top:${A.y}px;width:${len}px;transform:rotate(${ang}deg)"></div>`}).join("")}
function mpos(c){return{x:c.x*12,y:c.y*8.2}}
function hero(){let p=mpos(D.cities[save.city]);return`<div class="hero" style="left:${p.x}px;top:${p.y}px"><img src="${IMG.hero}"></div>`}
function tabs(){let tabs=[["home","🏠","Home"],["actions","⚡","Act"],["bank","🎒","Bank"],["craft","⚒️","Craft"],["more","☰","More"]];return`<nav class="tabs">${tabs.map(([id,ic,l])=>`<button class="tab ${save.screen===id?"active":""}" data-screen="${id}"><i>${ic}</i><span>${l}</span></button>`).join("")}</nav>`}
function bind(){document.querySelectorAll("[data-screen]").forEach(b=>b.onclick=()=>{save.screen=b.dataset.screen;persist();render()});document.querySelectorAll("[data-start]").forEach(b=>b.onclick=()=>start(b.dataset.start));document.querySelectorAll("[data-stop]").forEach(b=>b.onclick=stop);document.querySelectorAll("[data-city]").forEach(b=>b.onclick=()=>{let id=b.dataset.city;if(!canArea(id))return toast("Complete quest first");save.city=id;save.screen="actions";persist();render()});document.querySelectorAll("[data-equip]").forEach(b=>b.onclick=()=>equip(b.dataset.equip));document.querySelectorAll("[data-unequip]").forEach(b=>b.onclick=()=>unequip(b.dataset.unequip));document.querySelectorAll("[data-craft]").forEach(b=>b.onclick=()=>craft(b.dataset.craft));document.querySelectorAll("[data-buy]").forEach(b=>b.onclick=()=>buy(b.dataset.buy));document.querySelectorAll("[data-quest]").forEach(b=>b.onclick=()=>completeQuest(b.dataset.quest));document.querySelectorAll("[data-hatch]").forEach(b=>b.onclick=hatch);document.querySelectorAll("[data-item]").forEach(b=>b.onclick=()=>{let id=b.dataset.item;if(it(id).slot){save.screen="equip";persist();render()}else sell(id)});document.querySelector("[data-reset]")?.addEventListener("click",()=>{localStorage.removeItem(SAVE);save=null;render()});mapDrag()}
function fitMap(){let box=document.getElementById("mapBox");if(!box)return;if(!save.map)save.map={x:0,y:0,z:1};let w=box.clientWidth,h=box.clientHeight,scale=Math.max(w/1200,h/820);save.map.z=Math.max(.55,Math.min(1.2,scale*1.08));let p=mpos(D.cities[save.city]);save.map.x=w/2-p.x*save.map.z;save.map.y=h/2-p.y*save.map.z;clampMap()}
function clampMap(){let box=document.getElementById("mapBox");if(!box)return;let w=box.clientWidth,h=box.clientHeight,z=save.map.z;save.map.x=Math.min(40,Math.max(w-1200*z-40,save.map.x));save.map.y=Math.min(40,Math.max(h-820*z-40,save.map.y))}
function applyMap(){let el=document.getElementById("world");if(el)el.style.transform=`translate(${save.map.x}px,${save.map.y}px) scale(${save.map.z})`}
function mapDrag(){let box=document.getElementById("mapBox");if(!box)return;box.onpointerdown=e=>{if(e.target.closest("button"))return;drag={x:e.clientX,y:e.clientY,cx:save.map.x,cy:save.map.y};box.setPointerCapture(e.pointerId)};box.onpointermove=e=>{if(!drag)return;save.map.x=drag.cx+(e.clientX-drag.x);save.map.y=drag.cy+(e.clientY-drag.y);clampMap();applyMap()};box.onpointerup=()=>{drag=null;persist()};box.onpointercancel=box.onpointerup}
function live(){if(!save.action){setText("actName","Idle");setText("actTime","No assignment");let b=document.getElementById("actBar");if(b)b.style.width="0%";return}let a=D.actions[save.action.aid],elapsed=now()-save.action.start,cycle=a.sec*1000;setText("actName",a.n);setText("actTime",fmt(cycle-(elapsed%cycle)));let b=document.getElementById("actBar");if(b)b.style.width=`${(elapsed%cycle)/cycle*100}%`}
function setText(id,t){let e=document.getElementById(id);if(e)e.textContent=t}
window.addEventListener("resize",()=>{if(save&&save.screen==="map"){fitMap();persist();render()}});
load();render();setInterval(()=>{if(save){resolve();live()}},1000);
})();
